### PR TITLE
update openssl fetch

### PR DESCRIPTION
**Pull request by replabrobin**
Committer: Robin Becker <robin@reportlab.com>

### CODE REVIEW

**Comment by ogrisel** [comment]
The $COMMIT environment variable is undefined. I believe it should be changed to $TRAVIS_COMMIT. @njsmith @matthew-brett do you agree?

**Comment by ogrisel** [comment]
I made the change directly in this PR. Let's see if that fixes the travis build failure.

**Comment by replabrobin** [comment]
looks like that did it, don't know anything about travis, but well done

**Comment by ogrisel** [comment]
Merging then. Thanks for the fix @replabrobin.

**Comment by replabrobin** [comment]
great

**Pull request merged**
