### PR TITLE
Update patchelf from latest master to fix #78

### LINKED ISSUE #78: manylinux1 packages contain unstripped, but unstrippable, shared libraries
There are manylinux1 packages on PyPI that contain unstripped shared libraries that cause `strip` to fail.

```
dev@devenv:~$ virtualenv manylinux1_relocatable_test
New python executable in /home/dev/manylinux1_relocatable_test/bin/python
Installing setuptools, pip, wheel...done.
dev@devenv:~$ . manylinux1_relocatable_test/bin/activate
(manylinux1_relocatable_test) dev@devenv:~$ pip install cffi numpy
Collecting cffi
  Using cached cffi-1.7.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting numpy
  Using cached numpy-1.11.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pycparser (from cffi)
Installing collected packages: pycparser, cffi, numpy
Successfully installed cffi-1.7.0 numpy-1.11.1 pycparser-2.14
(manylinux1_relocatable_test) dev@devenv:~$ file manylinux1_relocatable_test/lib/python2.7/site-packages/_cffi_backend.so manylinux1_relocatable_test/lib/python2.7/site-packages/numpy/.libs/libopenblasp-r0-39a31c03.2.18.so
manylinux1_relocatable_test/lib/python2.7/site-packages/_cffi_backend.so:                             ELF 64-bit LSB  shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=d272756d64640cc3e6584d1a3db4ae0ae2990b48, not stripped
manylinux1_relocatable_test/lib/python2.7/site-packages/numpy/.libs/libopenblasp-r0-39a31c03.2.18.so: ELF 64-bit LSB  shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=85e6780ba62dd077bd2fbe1e765763d30ae25f10, not stripped
(manylinux1_relocatable_test) dev@devenv:~$ strip manylinux1_relocatable_test/lib/python2.7/site-packages/_cffi_backend.so manylinux1_relocatable_test/lib/python2.7/site-packages/numpy/.libs/libopenblasp-r0-39a31c03.2.18.so
BFD: manylinux1_relocatable_test/lib/python2.7/site-packages/stG8EFkj: Not enough room for program headers, try linking with -N
strip:manylinux1_relocatable_test/lib/python2.7/site-packages/stG8EFkj[.note.gnu.build-id]: Bad value
BFD: manylinux1_relocatable_test/lib/python2.7/site-packages/stG8EFkj: Not enough room for program headers, try linking with -N
strip:manylinux1_relocatable_test/lib/python2.7/site-packages/stG8EFkj: Bad value
BFD: manylinux1_relocatable_test/lib/python2.7/site-packages/numpy/.libs/stZ7PY7C: Not enough room for program headers, try linking with -N
strip:manylinux1_relocatable_test/lib/python2.7/site-packages/numpy/.libs/stZ7PY7C[.note.gnu.build-id]: Bad value
BFD: manylinux1_relocatable_test/lib/python2.7/site-packages/numpy/.libs/stZ7PY7C: Not enough room for program headers, try linking with -N
strip:manylinux1_relocatable_test/lib/python2.7/site-packages/numpy/.libs/stZ7PY7C: Bad value
```

This behavior has been observed on both Debian 8, Ubuntu 14.04, and Ubuntu 16.04.

If this is not a general artifact of the manylinux build process (and therefor not applicable to this project specifically), but a common (mis)configuration that affects multiple packages' manylinux1 build configuration/settings (eg cffi, numpy), then please let me know and I'll close this issue (and reopen it against the relevant projects).

### PR DESCRIPTION
**Pull request by sciyoshi**
Builds patchelf directly from latest source (which needs a newer automake). Fixes #78 and https://github.com/spotify/dh-virtualenv/issues/150, https://github.com/spotify/dh-virtualenv/issues/168, and https://github.com/spotify/dh-virtualenv/issues/203 among others.

### CODE REVIEW

**Comment by njsmith** [comment]
Thanks! This looks good to me, except: can you remove the checking of `PATCHELF_HASH`? In general github auto-generates archives on the fly and doesn't guarantee that they remain bit-for-bit identical over time. I know this is a common problem for release archives, [see e.g.](https://github.com/01org/parameter-framework/issues/372). I'm not sure if it applies for specific hash snapshots, but why risk it :-). The point of the hash checking is to reduce our potential attack surface, but we already trust github to manage the scripts themselves, so in this case it isn't adding much risk if we also trust github to deliver the snapshot we asked for.

**Comment by sciyoshi** [comment]
Good point @njsmith, removed the hash check.

**Comment by rmcgibbo** [comment]
This looks good to me.

**Comment by njsmith** [comment]
Awesome, thanks!

**Comment by njsmith** [comment]
(The docker images should be updated as soon as travis finishes, generally within the hour)

**Pull request merged**
