### PR TITLE
Upgrade to openssl-1.0.2h

### PR DESCRIPTION
**Pull request by ogrisel**
1.0.2g is vulnerable to multiple security issues:

https://mta.openssl.org/pipermail/openssl-announce/2016-April/000069.html

Here is the security advisory:

https://www.openssl.org/news/secadv/20160503.txt

### CODE REVIEW

**Comment by ogrisel** [comment]
I can reproduce the build failure when using curl version 7.15.5 from within the centos:5.11 docker image:

```
[root@81f854c5acc9 /]# curl -LO http://www.openssl.org/source/openssl-1.0.2h.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   316  100   316    0     0   2541      0 --:--:-- --:--:-- --:--:--     0
curl: (35) Unknown SSL protocol error in connection to www.openssl.org:443 
[root@81f854c5acc9 /]# curl -LO https://www.openssl.org/source/openssl-1.0.2h.tar.gz

curl: (35) Unknown SSL protocol error in connection to www.openssl.org:443 
```

**Comment by ogrisel** [comment]
The same download works on my workstation with curl 7.35.0.

**Comment by ogrisel** [comment]
Here is a sligthly more verbose error message:

```
[root@81f854c5acc9 /]# curl -v -LO https://www.openssl.org/source/openssl-1.0.2h.tar.gz
* About to connect() to www.openssl.org port 443
*   Trying 194.97.150.234... connected
* Connected to www.openssl.org (194.97.150.234) port 443
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSLv3, TLS handshake, Client hello (1):
Unknown SSL protocol error in connection to www.openssl.org:443 
* Closing connection #0

curl: (35) Unknown SSL protocol error in connection to www.openssl.org:443 
```

I also tried to manually update the `CURL_CA_CERT` to point to a local copy of http://curl.haxx.se/ca/cacert.pem but I still get the same error.

**Comment by ogrisel** [comment]
Using the FTP mirror seems to work (in my local docker container). Let's see if travis likes it too.

**Comment by ogrisel** [comment]
@njsmith @rmcgibbo @matthew-brett it would be great to merge this one as soon as travis is green to get the security fixes in.

**Comment by rmcgibbo** [comment]
LGTM. Merging.

**Comment by njsmith** [comment]
https://mobile.twitter.com/LGnome/status/727539621240827904

**Pull request merged**
