### PR TITLE
Add libtool

### PR DESCRIPTION
**Pull request by saghul**
Many libraries using autotools also use it.

### CODE REVIEW

**Comment by ogrisel** [comment]
LGTM. @njsmith @rmcgibbo any opinion?

**Comment by saghul** [comment]
Should I have any hope of this ever getting merged? I can rebase, but I'd rather not spend time on it if it won't be merged.

**Comment by rmcgibbo** [comment]
Yeah, I'll merge it.

**Comment by matthew-brett** [comment]
Robert - are you still planning to merge this one?

**Comment by rmcgibbo** [comment]
sure. it has conflicts tho.

**Pull request closed without merging**
