### PR TITLE
manylinux1_x86_64: Try to not install i686/i386

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by njsmith** [comment]
What does this do? Why did you need it?

**Comment by jcfr** [comment]
It decreases the size of the x86_64 image by not installing the i686/i386 packages.

Since I re-used the script of manylinux in a different context, I thought it would make sense to contribute this optimization.

**Comment by jcfr** [comment]
@njsmith  @matthew-brett  Anything I could do move this forward ? Thanks for your review and feedback.

**Comment by njsmith** [comment]
We can't really merge anything until openssl is fixed – right now the build would just fail anyway if we did.

**Comment by njsmith** [comment]
Travis is doing something weird here, going to try to close/reopen and see if that fixes it.

**Pull request merged**
