### PR TITLE
Revert "Merge pull request #273 from jcfr/add-cpython-3.8"

### PR DESCRIPTION
**Pull request by jcfr**
This reverts commit 2d39265ca399137180aadd26d29b2710ea0f2f92, reversing
changes made to d6b12a964120de4a4aa616783f1a73c6dda5e1f8.

### CODE REVIEW

**Comment by njsmith** [comment]
Thanks!

Are the pubkeys updates something that we want still?

**Comment by trishankatdatadog** [comment]
Wait, wait, wait --- why revert 3.8 now?

**Comment by njsmith** [comment]
@trishankatdatadog See conversation starting here: https://github.com/pypa/manylinux/pull/273#issuecomment-468796838

**Comment by trishankatdatadog** [comment]
Thanks @njsmith 🙇

**Pull request merged**
