### PR TITLE
[manylinux1] backport build

### PR DESCRIPTION
**Pull request by henryiii**
Followup to #941 for manylinux1.

### CODE REVIEW

**Comment by henryiii** [comment]
This would be _so_ much shorter if Python 2 was dropped. Why not drop Python 2 for manylinux1 as well? And drop Python 3.5 in May along with the other manylinuxes?

**Review by auvipy — APPROVED** [review]

**Comment by mayeut** [comment]
@henryiii,

I'm not planning to do any more work on `manylinux1` except bumping versions for updates. No new enhancements, no removals. Just basic support with feature freeze while waiting for EOL. We'll see how usage evolves by the end of the year and I can revisit this position at a later date depending on that.
Given you did the work for `build`, merging this enhancement hopping it won't get messy with dependabot.

**Comment by henryiii** [comment]
I would think that Python 2 removed from manylinux1, and Python 3.5 removed in May. By _not_ removing them, these are getting maintained _longer_ that if removed now. Someone using Python 2 is supposed to be using a pinned manylinux{^1} version already, why not require it across all manylinuxs? It would be much easier to drop Python 2 support in tools like cibuildwheel if all manylinuxs have dropped it. More importantly to me, Python 3.5 will "live" much longer if it's not removed when removed from the other manylinuxes in a few months. It's better to maintain less!

**Comment by henryiii** [comment]
PS: If you need me to, I'm happy to do a removal.

**Pull request merged**
