### PR TITLE
Update OpenSSL from 1.1.1d to 1.1.1e

### PR DESCRIPTION
**Pull request by manselmi**
Fixes a security issue: https://www.openssl.org/news/openssl-1.1.1-notes.html

### CODE REVIEW

**Comment by auvipy** [comment]
many linux images are failing

**Comment by manselmi** [comment]
Two builds failed.

In one build, curl failed with a "429 too many requests" while trying to download patchelf: https://travis-ci.org/github/pypa/manylinux/jobs/663980232#L3116  This failure seems like bad luck.

In the other build, curl failed with "SSL read: errno -5961" while trying to download Python: https://travis-ci.org/github/pypa/manylinux/jobs/663980231#L2460  Looking into that error code, I found this: https://serverfault.com/a/555336  After reading that I'm not sure if the error is a result of this PR or if there's some other networking issue that is causing it.

My first thought is to rerun the failed builds, although I'm not sure how to do that.  If they still fail then I wouldn't be sure how to proceed.  Any advice would be appreciated.

**Comment by auvipy** [comment]
I restarted the build

**Comment by michael-anselmi** [comment]
@auvipy Thank you!  It seems my suspicions were correct; all builds passed this time.

**Comment by manselmi** [comment]
@auvipy Thank you! It seems my suspicions were correct; all builds passed this time.

**Pull request merged**
