### PR TITLE
Including manylinux2010 in readme

### PR DESCRIPTION
**Pull request by armudgal**
Hi there,
As mentioned in #179.
I am not sure as `manylinux2010` will be replacing `manylinux1` or we still want to mention `manylinux1` in the readme. 

### According to me:
README should majorly talk about `manylinux2010` and include `manylinux1` briefly
but since `manylinux2010` is in demo phase, would that be a good idea?

Looking for opinions and suggestions.
Thanks

PS: Did a blunder in commit message, fixing it

### CODE REVIEW

**Comment by mayeut** [comment]
@armudgal, I agree that `README` in master should majorly talk about `manylinux2010`. I think a link shall be added to the `manylinux1` branch in order to redirect people that want information on `manylinux1` to that specific branch.

**Comment by armudgal** [comment]
Sure thanks. I will make the required changes.

**Comment by armudgal** [comment]
One bottleneck for this PR would be to merge https://github.com/pypa/python-manylinux-demo/pull/19 first, so that the demo is on the same page with this repository.

**Comment by mayeut** [comment]
@armudgal, 
There's still a reference to `PEP 513`in the docker image content. Can you change that as well please ?

**Comment by mayeut** [comment]
@armudgal, your commit mentions `Updating PEP number in Docker image content` but I'm not seeing any diffs in the file for that part.

**Comment by armudgal** [comment]
I did not stage that file by mistake. Apologies 🙉

**Comment by mayeut** [comment]
LGTM thanks.

**Pull request merged**
