### PR TITLE
docker/build_script: Update openssl to latest version: 1.0.2n -> 1.0.2o

### PR DESCRIPTION
**Pull request by jcfr**
See https://www.openssl.org/news/secadv/20180327.txt (thanks @natefoo for the link)

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @matthew-brett @njsmith

**Comment by jcfr** [comment]
Current download failure is quite strange:

```
+ wget ftp://ftp.openssl.org/source/openssl-1.0.2o.tar.gz
--2018-03-28 16:38:40--  ftp://ftp.openssl.org/source/openssl-1.0.2o.tar.gz
           => `openssl-1.0.2o.tar.gz'
Resolving ftp.openssl.org... 194.97.150.234, 2001:608:c00:180::1:ea
Connecting to ftp.openssl.org|194.97.150.234|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD /source ... done.
==> SIZE openssl-1.0.2o.tar.gz ... 5329472
==> PASV ... couldn't connect to 194.97.150.234 port 16022: No route to host
The command '/bin/sh -c linux32 bash build_scripts/build.sh && rm -r build_scripts' returned a non-zero code: 1
```

Locally, it works:

```
wget ftp://194.97.150.234/source/openssl-1.0.2o.tar.gz
--2018-03-28 16:50:13--  ftp://194.97.150.234/source/openssl-1.0.2o.tar.gz
           => ‘openssl-1.0.2o.tar.gz’
Connecting to 194.97.150.234:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /source ... done.
==> SIZE openssl-1.0.2o.tar.gz ... 5329472
==> PASV ... done.    ==> RETR openssl-1.0.2o.tar.gz ... done.
Length: 5329472 (5.1M) (unauthoritative)

openssl-1.0.2o.tar.gz                                     100%[=====================================================================================================================================>]   5.08M  1.26MB/s   in 6.4s   

2018-03-28 16:50:21 (816 KB/s) - ‘openssl-1.0.2o.tar.gz’ saved [5329472]

```

**Comment by jcfr** [comment]
Unless someone know why it is failing, next step would be to try locally downloading the travis docker image:

```
travis-job-3078caab-9b1a-4d9c-8ad1-ba3f4e78fc26 travis-ci-garnet-trusty-1512502259-986baf0
```

References:
* https://stackoverflow.com/questions/21053657/how-to-run-travis-ci-locally/49019950#49019950

**Comment by natefoo** [comment]
It appears to be a passive FTP problem, I'm not sure why this wouldn't have turned up before unless Travis has changed the way they handle outgoing ports. It'd probably be fine to switch to https, so [this](https://github.com/pypa/manylinux/blob/e662029e490b9b46df9d1ec0c09e3471e14a8c1b/docker/build_scripts/build_utils.sh#L8):

```sh
OPENSSL_DOWNLOAD_URL=ftp://ftp.openssl.org/source
```

becomes this:

```sh
OPENSSL_DOWNLOAD_URL=https://www.openssl.org/source
```

**Comment by jcfr** [comment]
> It'd probably be fine to switch to https

`ftp` is used because the centos based container do not support https. It is a chicken and egg problem.

A possible solution would be explicitly download the archive before [calling docker](https://github.com/pypa/manylinux/blob/e662029e490b9b46df9d1ec0c09e3471e14a8c1b/.travis.yml#L25-L26) and update the dockerbuild to copy the archive

**Comment by jcfr** [comment]
This seems to be a recent issue now documented in [travis-ci/travis-ci#9391: FTP connections on GCE (a.k.a. `sudo`-required) infrastructure are unreliable](https://github.com/travis-ci/travis-ci/issues/9391)

Look like the way forward is to retry the download.

**Comment by natefoo** [comment]
> I think `ftp` is used because the centos based container do not support https.

Sure enough, it even explains that in the comment right above the line I linked to.

I'll have a look at Travis and see what's changed.

**Comment by natefoo** [comment]
Beat me to it, ha! Thanks.

**Comment by jcfr** [comment]
In the mean time, this last commit should workaround the unreliable ftp download.

**Comment by jcfr** [comment]
@natefoo I also added you as co-author in the last commit. Let me know if you prefer not.

**Comment by jcfr** [comment]
Humm .. no luck with the re-try approach

**Comment by natefoo** [comment]
Rather than subshells, which break `set -e`, you can use a loop like:

```sh
for i in {0..4}; do
    wget ... && break
done || false
```

But, it looks like the "retry" method isn't working anyway.

**Comment by jcfr** [comment]
Thanks. I will remember this. 

I am backtracking these changes and downloading the file before calling `docker --build ...`

**Comment by natefoo** [comment]
Thanks for working on this. I made a small change to reduce some of the file handling complexity in jcfr/manylinux#1.

**Comment by jcfr** [comment]
Nice. The idea by not modifying the Dockerfile was to avoid hardcoding the version in a third place.

**Comment by njsmith** [comment]
The download-before-docker-build trick is a good idea! Maybe we should just do that in general for the bootstrap files (openssl and curl sources) instead of worrying about ftp and carefully chosen mirrors and stuff.

Would you be up for making the same change for curl? And you can drop the comments about working around travis's FTP bug, it's a silly bug but this way is better than what we were doing anyway.

**Comment by natefoo** [comment]
@njsmith Ok, in that case, I'll put in a little effort to adding a sources dir to the context and updating the build utils to be aware of that directory so we don't have to do a bunch of `COPY`s and then moving sources to cwd in the build script.

**Comment by jcfr** [comment]
> Can you squash the commits once it's ready to go?

All set. See https://github.com/pypa/manylinux/pull/172

But for some reason the CI didn't kick in.

> The download-before-docker-build trick is a good idea! Maybe we should just do that in general for the bootstrap files

:+1:

**Comment by jcfr** [comment]
> I'll put in a little effort to adding a sources dir

@natefoo I will let you takes the lead now.

**Comment by jcfr** [comment]
Closing. This is superseded by #172

**Pull request closed without merging**
