### PR TITLE
Update patchelf to 0.13

### PR DESCRIPTION
**Pull request by lpsinger**

### CODE REVIEW

**Review by auvipy — APPROVED** [review]
is the travis failures related?

**Comment by lpsinger** [comment]
I don't think so.

**Comment by lpsinger** [comment]
When will this be merged? One of our packages is affected by a bug in patchelf that was fixed in version 0.13 (see https://git.ligo.org/lscsoft/lalsuite/-/issues/459#note_409265) and we cannot release until this is fixed in manylinux.

**Comment by lpsinger** [comment]
Thanks!

**Pull request merged**
