### PR TITLE
Build scripts cleanup

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
@njsmith  In addition of few aesthetic cleanups, this PR has also the advantage of removing the curl `tar.gz` archive and saving few  MBs.

It is ready to be merged.

**Comment by jcfr** [comment]
@njsmith  @matthew-brett What is the process to get this integrated ?

**Comment by njsmith** [comment]
Are the changes here still correct now that #174 was merged? (They both have some mention of curl...)

**Comment by jcfr** [comment]
> Are the changes here still correct now that #174 was merged?

Indeed. Topic was rebased and CI is green.

**Comment by natefoo** [comment]
With the switch back to the canonical archive, the old `curl-*` path should be correct (`curl_*` was for the debian archive.

**Comment by jcfr** [comment]
> the old curl-* path should be correct (curl_*

Indeed :+1:  Updated topic pushed (from :airplane: )

**Pull request merged**
