### PR TITLE
Support PyPy

### PR DESCRIPTION
**Pull request by ofek**
I can't test docker locally easily, but this should work. Caveat emptor: this only supports PyPy x86_64.

### CODE REVIEW

**Comment by ofek** [comment]
@njsmith @matthew-brett @ogrisel @rmcgibbo @natefoo Do any of you know why the build failed? There is nothing useful in the report.

**Comment by ofek** [comment]
*respectful bump*

**Comment by rmcgibbo** [comment]
i think the EPEL checksum online must have changed.

**Comment by rmcgibbo** [comment]
This is why:

```
mcgibbon@wks
$ curl -sLO https://dl.fedoraproject.org/pub/epel/5/x86_64/epel-release-5-4.noarch.rpm

mcgibbon@wks
$ cat epel-release-5-4.noarch.rpm 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /pub/epel/5/x86_64/epel-release-5-4.noarch.rpm was not found on this server.</p>
</body></html>
```

**Comment by rmcgibbo** [comment]
I think the master branch may be fixed by #107 now, @ofek.

**Comment by ofek** [comment]
@rmcgibbo I'll sync when that PR gets merged, thank you!

**Comment by squeaky-pl** [comment]
Please note that 5.7.1 was the last version I was building against CentOS 5. All the future versions will be built against CentOS 6.

IMHO it would be better to include PyPy as part of the future manylinux2 tag. Apart I am not providing i686 builds anymore since the downloads for them fell below 1% long time ago. People using PyPy are more likely to run x86_64 architecture were PyPy can optimize much better.

**Comment by ofek** [comment]
@rmcgibbo Can you spot why ln is failing?

**Comment by rmcgibbo** [comment]
sorry, not sure.

**Comment by ofek** [comment]
@squeaky-pl Do you have any idea why this might be failing? https://travis-ci.org/pypa/manylinux/jobs/223351424#L1295

**Comment by squeaky-pl** [comment]
@ofek PyPy3 5.7.1 is already based on Centos 6 so it wont work. PyPy3 itself does not work on CentOS 5 since it requires some symbols during translation that are not available on CentOS 5. Only PyPy2 5.7.1 will work on CentOS 5.

**Comment by ofek** [comment]
@squeaky-pl Is this incorrect then? https://github.com/squeaky-pl/portable-pypy/issues/50#issuecomment-294803878

**Comment by squeaky-pl** [comment]
@ofek yes. I should be more specific, only PyPy2 5.7.1 works on CentOS 5.

**Comment by ofek** [comment]
Well then... this won't work. Feel free to close this PR when ready. Where can one find out more about manylinux2?

**Comment by squeaky-pl** [comment]
manylinux2 is an upcoming? tag based on CentOS 6 probably. Somebody needs to write a PEP, prepare Docker images and test if popular packages are building against it. I guess the mailining list is a place to ask.

**Pull request closed without merging**
