### PR TITLE
Upgrade patchelf to 0.12

### PR DESCRIPTION
**Pull request by radarhere**
See #735

### CODE REVIEW

**Comment by alex** [comment]
I'd think you need to revert the patching portions of https://github.com/pypa/manylinux/pull/739 as well.

**Comment by radarhere** [comment]
Yes and no - that change was made on the manylinux2014 branch, and this PR is for the master branch. Apologies for not understanding the branch structure here - is this PR unhelpful?

**Comment by radarhere** [comment]
For the record, the reversion has now been done in #741

**Comment by mattip** [comment]
This PR does not really address #735 since that issue is arm64-specific. There may be other reasons to update patchelf, so I think it is worthwhile. One for the manylinux1 branch would bring all the branches into sync.

**Comment by mayeut** [comment]
Thanks @radarhere. I also created a PR for manylinux1 to bring all the branches into sync.

**Pull request merged**
