### PR TITLE
feat: use GHA to build s390x/ppc64le images

### PR DESCRIPTION
**Pull request by mayeut**
workaround travis CI issues

### CODE REVIEW

**Comment by EwoutH** [comment]
All green! 🎉

**Comment by EwoutH** [comment]
Since the deploy step was skipped in the PR, we have to wait about 6 hours until, it finishes on the main branch right?

**Comment by mayeut** [comment]
> we have to wait about 6 hours until, it finishes on the main branch right?

right

**Comment by EwoutH** [comment]
But glad to see it worked, thanks!

**Pull request merged**
