### PR TITLE
Build hardening

### PR DESCRIPTION
**Pull request by mayeut**
- Use hardening for building all tools & libraries
This does not affect the wheels that are produced by end users as proposed in #59 but mitigates potential security issues in the tools used by manylinux images as mentioned in #1005
- Always update system packages in the final step
Since docker cache is used, system packages are not updated when cache is present. Always update them in the final step.

### CODE REVIEW

**Comment by mayeut** [comment]
@trishankatdatadog, @aws-taylor,  @wallrj,

Any thoughts on this PR ?

**Comment by trishankatdatadog** [comment]
Good idea. What about all the [other default flags](https://wiki.ubuntu.com/ToolChain/CompilerFlags#Default_Flags)?

**Comment by mayeut** [comment]
All other flags I can think of for security purposes do not work on those old distros:
```
-fPIE / -Wl,-pie
-fstack-clash-protection
-fcf-protection
```

**Comment by trishankatdatadog** [comment]
> All other flags I can think of for security purposes do not work on those old distros:

Understood. If so, let's link to that document I sent, and comment on why we turned on only some flags and not others?

**Pull request merged**
