### PR TITLE
Fail on curl error (e.g., during SSL / TLS)

### PR DESCRIPTION
**Pull request by trishankatdatadog**
Slightly stricter checking on curl: fail on error (e.g, during SSL / TLS session. But this is not critical because:
1. We can always check hashes.
2. We should ideally update curl to the latest version as early as possible.

### CODE REVIEW

**Comment by rmcgibbo** [comment]
LGTM. +1

**Comment by njsmith** [comment]
This has several conflicts with #130, whose resolution aren't immediately obvious to me.

**Comment by trishankatdatadog** [comment]
@njsmith Let me take a look as soon as I can!

**Comment by trishankatdatadog** [comment]
@njsmith Should be mergeable now, please take a look? Thanks!

**Comment by njsmith** [comment]
@trishankatdatadog Github's still showing the same three conflicts... not sure what's up with that. I've had it happen before that I had to click the "Resolve conflicts" button twice before Github actually resolved the conflicts. 🤷‍

**Comment by trishankatdatadog** [comment]
@njsmith Resolved again :) GitHub finally reports no conflicts now. Waiting to see if tests pass.

**Comment by njsmith** [comment]
Thanks! Sorry about that... no idea why Github does that, but it's pretty annoying.

**Pull request merged**
